### ISSUE TITLE
It seems like the new version does not work

### ISSUE THREAD

**Issue by TheButterbrotMan** [ModdingX/ModListCreator#10]
https://imgur.com/a/Ed9k0R6

**Comment by MelanX** [comment]
Sadly, I can't reproduce the issue.
Could you provide more information? 
- What command did you use *exactly* to start the tool?
- Your manifest/zip

During development, I had the same problem but I already fixed it. This is why this confuses me that much.
You could also try again with the new version 2.0.1.

**Comment by TheButterbrotMan** [comment]
I used:

$ java -jar ModListCreator-<version>.jar --html

on https://www.curseforge.com/minecraft/modpacks/deathdusk

**Comment by MelanX** [comment]
With a zip or the `manifest.json`?

**Comment by TheButterbrotMan** [comment]
manifest.json

**Comment by MelanX** [comment]
Sorry for the long waiting time on this issue. Just wanted to let you know that I finally tested this (with 3.0.1) and that works fine :)
