### ISSUE TITLE
O(1) instead of O(N) api calls to resolve the authors?

### ISSUE THREAD

**Issue by Quezler** [ModdingX/ModListCreator#11]
Currently each mod is requested one-by-one (and again for each file) whilst your cursewrapper already has code in place to request all mods in bulk, yet there seems to be no active api endpoint for it: https://github.com/ModdingX/CurseWrapper/blob/764ea465ada6d0548d3a2fb67eb424e8d579b993/Server/src/main/java/org/moddingx/cursewrapper/route/CommonCacheResolvers.java#L35

Do you happen to have any plans for it?

**Comment by MelanX** [comment]
Good point! I never really re-written this tool by using the cursewrapper, just adjusted everything, so it uses it. I will use this method and maybe find other things to improve as well. Thank you!

**Comment by Quezler** [comment]
If you would like some help, hit me up ^-^

(I'll be needing a bulk post/get `https://curse.melanx.de/projects` first to test with before being any help on this repo)

**Comment by noeppi-noeppi** [comment]
> (I'll be needing a bulk post/get `https://curse.melanx.de/projects` first to test with before being any help on this repo)

Added! (CurseWrapper 2.1)
