### ISSUE TITLE
Frequent StatusCode 500+ when using

### ISSUE THREAD

**Issue by NielsPilgaard** [ModdingX/ModListCreator#13]
Hey there \o

When using the ModListCreator, it frequently crashes before finishing.

Crash: https://gist.github.com/NielsPilgaard/8452fdea3fe815b993ecae619d29dc12

Let me know if there's anything I can do to help :)

**Comment by MelanX** [comment]
Unfortunately, that’s the CurseForge API. The wrapper I’m using is fine, it’s relaying to CurseForge and they cause the problems. The wrapper has caches, but sadly it still happens. I tested stuff 2 hours ago (when you reported this) and had the same problem :/

**Comment by NielsPilgaard** [comment]
Ouch, alright 👍
