### ISSUE TITLE
Changelog generator lists unchanged mods as changed

### ISSUE THREAD

**Issue by NielsPilgaard** [ModdingX/ModListCreator#16]
I think this gives a pretty good picture of the bug: 
https://gist.github.com/NielsPilgaard/a150ac8371050c4d2c341255fb043186

**Comment by MelanX** [comment]
I hope it's better now!

**Comment by NielsPilgaard** [comment]
Much, thank you kindly!

New gist, just if you're curious: https://gist.github.com/NielsPilgaard/db875940a006118b58a1d6ccd57dc457

**Comment by MelanX** [comment]
Perfect!
