### ISSUE TITLE
[feature request] mount the pack

### ISSUE THREAD

**Issue by kreezxil** [ModdingX/ModListCreator#5]
instead of going thru the hoops of extracting a manifest, allow us to specify the pack, you can then either mount it and get the manifest, or you can unzip it and get it, or however you want to do that.

I recommended a similar feature to changeloggenerator and he added it.

**Comment by NielsPilgaard** [comment]
I would also appreciate this feature, it would make modlist generation in GitHub Actions far simpler :)

**Comment by NielsPilgaard** [comment]
How is this used? I tried setting --manifest to a zip with a manifest inside and it went absolutely crazy.

**Comment by MelanX** [comment]
ehm.. because you opened an issue, i think you fixed it? otherwise you could tell me more about it. On Enigmatica or BisectHosting discord or DM. I'm MelanX#7949 on Discord. I think it's easier to communicate this way and give support :)

**Comment by NielsPilgaard** [comment]
Not fixed sadly, will give you a pm.
