### ISSUE TITLE
Modlist is no longer sorted

### ISSUE THREAD

**Issue by NielsPilgaard** [ModdingX/ModListCreator#8]
I used `ModlistCreator-1.2.0` on Enigmatica 6 v0.4.10, which resulted in this file: https://github.com/NillerMedDild/Enigmatica6/blob/master/MODLIST.md

It used to be sorted, not so much anymore :P

Side-note: Thanks for fixing the links and adding logging to the Creator :D

**Comment by MelanX** [comment]
oh.. :D that's not cool :D I changed the sorting algorithm a bit and.. yes :D thanks for reporting!

**Comment by NielsPilgaard** [comment]
Oh and a few of the names seem off, for example:

- [1.16.2 - 1.16.5 (3.2.0)](https://www.curseforge.com/minecraft/mc-mods/magic-feather/files/3224434) (by [Ephys](https://www.curseforge.com/members/ephys/projects))
- [1.5.2 (Forge 1.16.5)](https://www.curseforge.com/minecraft/mc-mods/spark/files/3245792) (by [Iucko](https://www.curseforge.com/members/iucko/projects))

It seems to be because of poorly picked file names, not sure what there is to do about that if anything :P

**Comment by MelanX** [comment]
Yes, the problem is that they name the files very weird.. can't really fix it :/

**Comment by NielsPilgaard** [comment]
Worked flawlessly, nice one 👍
