### ISSUE TITLE
Possible to list mods that are server side/client side only?

### ISSUE THREAD

**Issue by tobi-polar** [ModdingX/ModListCreator#9]
Just and idea, not sure if possible, but it would be helpful to generate a list of mods that can be optionally client/server side only. I guess this only really works if the mod declares whether it's client side or server side only.

**Comment by MelanX** [comment]
It really would be an awesome feature but unfortunately you’re right. The data for that is not given :/ this will never be possible (unless CurseForge would add this but I don’t think so)
Thank you anyway for this idea!
